# Generated by Django 5.2.5 on 2025-08-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='risk_profile',
            field=models.CharField(choices=[('conservative', 'Conservador'), ('moderate', 'Moderado'), ('aggressive', 'Arriesgado')], default='moderate', help_text='Selecciona tu perfil de inversión según tu tolerancia al riesgo', max_length=12, verbose_name='Perfil de Riesgo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualizacion'),
        ),
    ]
