# Generated by Django 5.2.5 on 2025-09-18 00:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbolo', models.CharField(help_text='Símbolo del activo (ej: AAPL, USD/COP)', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre completo del activo', max_length=200)),
                ('tipo', models.CharField(choices=[('ACCION', 'Acción'), ('ETF', 'ETF'), ('DIVISA', 'Divisa')], help_text='Tipo de activo financiero', max_length=10)),
                ('precio_actual', models.DecimalField(decimal_places=4, help_text='Precio actual del activo', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('precio_anterior', models.DecimalField(decimal_places=4, help_text='Precio del cierre anterior', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('volumen', models.BigIntegerField(help_text='Volumen de transacciones', validators=[django.core.validators.MinValueValidator(0)])),
                ('mercado', models.CharField(help_text='Mercado donde se cotiza (ej: NYSE, NASDAQ, FX)', max_length=100)),
                ('moneda', models.CharField(default='USD', help_text='Moneda de cotización', max_length=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Activo Financiero',
                'verbose_name_plural': 'Activos Financieros',
                'ordering': ['tipo', 'simbolo'],
            },
        ),
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('activo_financiero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detalle_accion', serialize=False, to='mercado_financiero.activofinanciero')),
                ('sector', models.CharField(help_text='Sector económico (ej: Tecnología, Salud, Financiero)', max_length=100)),
                ('empresa', models.CharField(help_text='Nombre de la empresa', max_length=200)),
                ('capitalizacion_mercado', models.BigIntegerField(blank=True, help_text='Capitalización de mercado en USD', null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Acción',
                'verbose_name_plural': 'Acciones',
            },
        ),
        migrations.CreateModel(
            name='Divisa',
            fields=[
                ('activo_financiero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detalle_divisa', serialize=False, to='mercado_financiero.activofinanciero')),
                ('moneda_base', models.CharField(help_text='Moneda base del par (ej: USD en USD/COP)', max_length=10)),
                ('moneda_cotizacion', models.CharField(help_text='Moneda de cotización del par (ej: COP en USD/COP)', max_length=10)),
                ('tipo_cambio_referencia', models.DecimalField(blank=True, decimal_places=6, help_text='Tipo de cambio de referencia del banco central', max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'Divisa',
                'verbose_name_plural': 'Divisas',
            },
        ),
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('activo_financiero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detalle_etf', serialize=False, to='mercado_financiero.activofinanciero')),
                ('categoria', models.CharField(help_text='Categoría del ETF (ej: S&P 500, Commodities, Bonds)', max_length=100)),
                ('ratio_gastos', models.DecimalField(blank=True, decimal_places=4, help_text='Ratio de gastos del ETF (%)', max_digits=5, null=True)),
                ('activos_bajo_gestion', models.BigIntegerField(blank=True, help_text='Activos bajo gestión en USD', null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'ETF',
                'verbose_name_plural': 'ETFs',
            },
        ),
        migrations.AddIndex(
            model_name='activofinanciero',
            index=models.Index(fields=['tipo'], name='mercado_fin_tipo_c83243_idx'),
        ),
        migrations.AddIndex(
            model_name='activofinanciero',
            index=models.Index(fields=['simbolo'], name='mercado_fin_simbolo_0c66ad_idx'),
        ),
        migrations.AddIndex(
            model_name='activofinanciero',
            index=models.Index(fields=['fecha_actualizacion'], name='mercado_fin_fecha_a_3d7370_idx'),
        ),
    ]
