# Generated by Django 5.2.5 on 2025-10-02 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('currency', 'Currency')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('volume', models.BigIntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_series', to='stocks.financialasset')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('asset', 'date')},
            },
        ),
    ]
