# Generated by Django 5.2.5 on 2025-10-03 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('daily_change_percent', models.FloatField(blank=True, null=True)),
                ('five_day_change_percent', models.FloatField(blank=True, null=True)),
                ('monthly_change_percent', models.FloatField(blank=True, null=True)),
                ('yearly_change_percent', models.FloatField(blank=True, null=True)),
                ('five_year_change_percent', models.FloatField(blank=True, null=True)),
                ('day_high', models.FloatField(blank=True, null=True)),
                ('day_low', models.FloatField(blank=True, null=True)),
                ('fifty_two_week_high', models.FloatField(blank=True, null=True)),
                ('fifty_two_week_low', models.FloatField(blank=True, null=True)),
                ('bid', models.FloatField(blank=True, null=True)),
                ('ask', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency_metrics', to='stocks.financialasset')),
            ],
        ),
        migrations.CreateModel(
            name='ETFMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('daily_change_percent', models.FloatField(blank=True, null=True)),
                ('change_5d_percent', models.FloatField(blank=True, null=True)),
                ('change_1m_percent', models.FloatField(blank=True, null=True)),
                ('change_ytd_percent', models.FloatField(blank=True, null=True)),
                ('change_5y_percent', models.FloatField(blank=True, null=True)),
                ('day_high', models.FloatField(blank=True, null=True)),
                ('day_low', models.FloatField(blank=True, null=True)),
                ('week52_high', models.FloatField(blank=True, null=True)),
                ('week52_low', models.FloatField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('dividend_yield', models.FloatField(blank=True, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('beta', models.FloatField(blank=True, null=True)),
                ('nav', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etf_metrics', to='stocks.financialasset')),
            ],
        ),
        migrations.CreateModel(
            name='StockMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('daily_change', models.FloatField(blank=True, null=True)),
                ('change_5d', models.FloatField(blank=True, null=True)),
                ('change_1m', models.FloatField(blank=True, null=True)),
                ('change_ytd', models.FloatField(blank=True, null=True)),
                ('change_5y', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('pe_ratio', models.FloatField(blank=True, null=True)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('dividend_yield', models.FloatField(blank=True, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='stocks.financialasset')),
            ],
        ),
    ]
