# Generated by Django 5.2.5 on 2025-10-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_currencymetrics_etfmetrics_stockmetrics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencymetrics',
            old_name='five_day_change_percent',
            new_name='change_1m_percent',
        ),
        migrations.RenameField(
            model_name='currencymetrics',
            old_name='five_year_change_percent',
            new_name='change_5d_percent',
        ),
        migrations.RenameField(
            model_name='currencymetrics',
            old_name='monthly_change_percent',
            new_name='change_5y_percent',
        ),
        migrations.RenameField(
            model_name='currencymetrics',
            old_name='yearly_change_percent',
            new_name='change_ytd_percent',
        ),
        migrations.RenameField(
            model_name='stockmetrics',
            old_name='change_1m',
            new_name='change_1m_percent',
        ),
        migrations.RenameField(
            model_name='stockmetrics',
            old_name='change_5d',
            new_name='change_5d_percent',
        ),
        migrations.RenameField(
            model_name='stockmetrics',
            old_name='change_5y',
            new_name='change_5y_percent',
        ),
        migrations.RenameField(
            model_name='stockmetrics',
            old_name='change_ytd',
            new_name='change_ytd_percent',
        ),
    ]
