# Generated by Django 5.2.5 on 2025-10-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_rename_five_day_change_percent_currencymetrics_change_1m_percent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyMetrics',
        ),
    ]
