# Generated by Django 5.2.5 on 2025-10-03 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_delete_currencymetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('daily_change_percent', models.FloatField(blank=True, null=True)),
                ('change_5d_percent', models.FloatField(blank=True, null=True)),
                ('change_1m_percent', models.FloatField(blank=True, null=True)),
                ('change_ytd_percent', models.FloatField(blank=True, null=True)),
                ('change_5y_percent', models.FloatField(blank=True, null=True)),
                ('day_high', models.FloatField(blank=True, null=True)),
                ('day_low', models.FloatField(blank=True, null=True)),
                ('fifty_two_week_high', models.FloatField(blank=True, null=True)),
                ('fifty_two_week_low', models.FloatField(blank=True, null=True)),
                ('bid', models.FloatField(blank=True, null=True)),
                ('ask', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency_metrics', to='stocks.financialasset')),
            ],
        ),
    ]
