# Generated by Django 5.2.5 on 2025-10-03 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_currencymetrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etfmetrics',
            name='beta',
        ),
    ]
