# Generated by Django 5.2.5 on 2025-10-03 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_remove_etfmetrics_beta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencymetrics',
            old_name='current_price',
            new_name='exchange_rate',
        ),
    ]
